B dev
Ayobami6/MeetDevs pull request #79
Opened 2023-10-19 08:42 UTC by betiniakarandut

1. Merge series of conflicts
2. Feat: Implemented the ProfileDropDownMenu for talent avatar

2023-10-19 09:21 UTC, Ayobami6 requested changes
Bro, This is a lot of conflict, please pull first from staging to local branch, then fix the conflicts you might, after then make another PR from your updated branch

2023-10-19 10:50 UTC, Ayobami6 commented on server/controllers/offerController.ts
It looks like you have 2 getOfferByTalent and getOfferByEmployer methods here,  So it's not allowing the application build or bundle

2023-10-19 18:39 UTC, betiniakarandut commented on server/controllers/offerController.ts
Duplicates removed. It is running smooth on my end now.

2023-10-20 21:27 UTC, Ayobami6 approved these changes
Alright thanks, I will fix the test from here

2023-10-20 21:27 UTC, merged